<?php
$dom_perspectiva = "&lt;mxGraphModel&gt;
&lt;root&gt;
  &lt;Diagram label=&quot;My Diagram&quot; href=&quot;http://www.jgraph.com/&quot; id=&quot;0&quot;&gt;
    &lt;mxCell/&gt;
  &lt;/Diagram&gt;
  &lt;Layer label=&quot;Default Layer&quot; id=&quot;1&quot;&gt;
    &lt;mxCell parent=&quot;0&quot;/&gt;
  &lt;/Layer&gt;
  &lt;Shape label=&quot;Shape&quot; href=&quot;&quot; id=&quot;2&quot;&gt;
    &lt;mxCell style=&quot;doubleEllipse&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;100&quot; y=&quot;250&quot; width=&quot;60&quot; height=&quot;60&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Shape&gt;
  &lt;Shape label=&quot;Shape&quot; href=&quot;&quot; id=&quot;3&quot;&gt;
    &lt;mxCell style=&quot;doubleEllipse&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;600&quot; y=&quot;330&quot; width=&quot;60&quot; height=&quot;60&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Shape&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;4&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;2&quot; target=&quot;3&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Shape label=&quot;Shape&quot; href=&quot;&quot; id=&quot;5&quot;&gt;
    &lt;mxCell style=&quot;doubleEllipse&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;540&quot; y=&quot;60&quot; width=&quot;60&quot; height=&quot;60&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Shape&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;6&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;2&quot; target=&quot;5&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;7&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;5&quot; target=&quot;3&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Shape label=&quot;Shape&quot; href=&quot;&quot; id=&quot;8&quot;&gt;
    &lt;mxCell style=&quot;doubleEllipse&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;770&quot; y=&quot;230&quot; width=&quot;60&quot; height=&quot;60&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Shape&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;9&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;3&quot; target=&quot;8&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Shape label=&quot;Shape&quot; href=&quot;&quot; id=&quot;10&quot;&gt;
    &lt;mxCell style=&quot;doubleEllipse&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;430&quot; y=&quot;210&quot; width=&quot;60&quot; height=&quot;60&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Shape&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;11&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;3&quot; target=&quot;10&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Shape label=&quot;Shape&quot; href=&quot;&quot; id=&quot;12&quot;&gt;
    &lt;mxCell style=&quot;doubleEllipse&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;220&quot; y=&quot;360&quot; width=&quot;60&quot; height=&quot;60&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Shape&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;13&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;2&quot; target=&quot;12&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Roundrect label=&quot;Rounded&quot; href=&quot;&quot; id=&quot;14&quot;&gt;
    &lt;mxCell style=&quot;rounded&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;100&quot; y=&quot;420&quot; width=&quot;80&quot; height=&quot;40&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Roundrect&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;15&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;2&quot; target=&quot;14&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Roundrect label=&quot;Rounded&quot; href=&quot;&quot; id=&quot;16&quot;&gt;
    &lt;mxCell style=&quot;rounded&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;180&quot; y=&quot;100&quot; width=&quot;80&quot; height=&quot;40&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Roundrect&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;17&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;14&quot; target=&quot;16&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Roundrect label=&quot;Rounded&quot; href=&quot;&quot; id=&quot;18&quot;&gt;
    &lt;mxCell style=&quot;rounded&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;810&quot; y=&quot;70&quot; width=&quot;80&quot; height=&quot;40&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Roundrect&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;19&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;16&quot; target=&quot;18&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Shape label=&quot;Shape&quot; href=&quot;&quot; id=&quot;20&quot;&gt;
    &lt;mxCell style=&quot;doubleEllipse&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;1050&quot; y=&quot;250&quot; width=&quot;60&quot; height=&quot;60&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Shape&gt;
  &lt;Connector label=&quot;&quot; href=&quot;&quot; id=&quot;21&quot;&gt;
    &lt;mxCell parent=&quot;1&quot; source=&quot;8&quot; target=&quot;20&quot; edge=&quot;1&quot;&gt;
      &lt;mxGeometry relative=&quot;1&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Connector&gt;
  &lt;Shape label=&quot;Shape&quot; href=&quot;&quot; id=&quot;22&quot;&gt;
    &lt;mxCell style=&quot;actor&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;
      &lt;mxGeometry x=&quot;480&quot; y=&quot;430&quot; width=&quot;250&quot; height=&quot;60&quot; as=&quot;geometry&quot;/&gt;
    &lt;/mxCell&gt;
  &lt;/Shape&gt;
&lt;/root&gt;
&lt;/mxGraphModel&gt;";

?>